### PR TITLE
remove reference to window in override console

### PR DESCRIPTION
**Pull request by jtisekar**
replacing the reference to window.console to just console so that it works in Node.

### CODE REVIEW

**Comment by horvay** [comment]
Wow, does this work for web too?

**Comment by jtisekar** [comment]
yes, it does work for both

**Comment by horvay** [comment]
I will update the npm package in a few hours. I have a vet appointment (not for me.)

**Comment by jtisekar** [comment]
awesome !

**Comment by jtisekar** [comment]
Did you get a chance to update the npm package

**Comment by horvay** [comment]
I sure did. Try it out

**Comment by jtisekar** [comment]
Works great now.  Thank you !

**Pull request merged**
